version: '3.9'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=nextcloud_swarm_01_trusted_proxies
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=nextcloud_swarm_01_overwritecliurl
      - OVERWRITEHOST=nextcloud_swarm_01_secret_overwritehost
    secrets: 
      - nextcloud_swarm_01_trusted_proxies
      - nextcloud_swarm_01_overwritecliurl
      - nextcloud_swarm_01_secret_overwritehost
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    image: momab/private_01
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

secrets: 
  - nextcloud_swarm_01_trusted_proxies
  - nextcloud_swarm_01_overwritecliurl
  - nextcloud_swarm_01_secret_overwritehost
  
volumes:
  db:
  nextcloud:
  nextcloud-data:
  nextcloud-config: